### ISSUE TITLE
PHP strings are grey instead of blue

### ISSUE THREAD

**Issue by Starfox64** [Yummygum/city-lights-syntax-atom#25] opened 2018-10-12 13:22 UTC
If you look at the following image, strings are grey instead of blue
![image](https://user-images.githubusercontent.com/1530720/46871611-32287900-ce32-11e8-813d-6221a505ab39.png)

Scope for PHP strings:

- text.html.php
- meta.embedded.block.php
- source.php
- meta.switch-statement.php
- meta.function-call.php
- meta.switch-statement.php
- meta.function-call.php
- string.quoted.single.php
- string.quoted.double.php

**Comment by noudadrichem** [comment] 2018-10-12 19:21
Hi @Starfox64 ,

This is intended because if you mix PHP with HTML tags the PHP code better to distinct.

Closing this because it's not a bug nor real issue. 

_You might be able to add the colors to your own theme stylesheet. 😊_

**Closed as completed by noudadrichem** 2018-10-12 19:21 UTC
